# Generated by Django 4.1.3 on 2022-11-21 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ActSheetApp', '0002_branch_tb'),
    ]

    operations = [
        migrations.CreateModel(
            name='shift_tb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_time', models.CharField(default='', max_length=100)),
                ('to_time', models.CharField(default='', max_length=100)),
            ],
        ),
    ]
