# Generated by Django 4.1.3 on 2022-11-21 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ActSheetApp', '0003_shift_tb'),
    ]

    operations = [
        migrations.CreateModel(
            name='zone_tb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zone', models.CharField(default='', max_length=100)),
                ('created_at', models.CharField(default='', max_length=100)),
                ('updated_at', models.CharField(default='', max_length=100)),
            ],
        ),
    ]
