# Generated by Django 4.1.3 on 2022-11-21 11:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ActSheetApp', '0004_zone_tb'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin_tb',
            name='created_at',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='admin_tb',
            name='updated_at',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='branch_tb',
            name='created_at',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='branch_tb',
            name='updated_at',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='shift_tb',
            name='created_at',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='shift_tb',
            name='updated_at',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='zone_tb',
            name='branch_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='ActSheetApp.branch_tb'),
        ),
    ]
