# Generated by Django 4.1.3 on 2022-11-21 12:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ActSheetApp', '0005_admin_tb_created_at_admin_tb_updated_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='window_zone_tb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zone', models.CharField(default='', max_length=100)),
                ('created_at', models.CharField(default='', max_length=100)),
                ('updated_at', models.CharField(default='', max_length=100)),
                ('branch_id', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='ActSheetApp.branch_tb')),
            ],
        ),
    ]
