# Generated by Django 4.1.3 on 2022-11-23 04:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ActSheetApp', '0008_team_leader_tb_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team_leader_tb',
            name='branch_id',
        ),
    ]
