# Generated by Django 4.1.3 on 2022-11-23 05:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ActSheetApp', '0009_remove_team_leader_tb_branch_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='agent_tb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('email', models.CharField(default='', max_length=100)),
                ('phone', models.CharField(default='', max_length=100)),
                ('password', models.CharField(default='', max_length=100)),
                ('created_at', models.CharField(default='', max_length=100)),
                ('updated_at', models.CharField(default='', max_length=100)),
                ('team_leader_id', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='ActSheetApp.team_leader_tb')),
            ],
        ),
    ]
