# Generated by Django 4.1.3 on 2022-11-25 08:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ActSheetApp', '0010_agent_tb'),
    ]

    operations = [
        migrations.CreateModel(
            name='client_tb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('email', models.CharField(default='', max_length=100)),
                ('phone', models.CharField(default='', max_length=100)),
                ('business', models.CharField(default='', max_length=100, null=True)),
                ('password', models.CharField(default='', max_length=100)),
                ('created_at', models.CharField(default='', max_length=100)),
                ('updated_at', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='branch_tb',
            name='location',
        ),
        migrations.AddField(
            model_name='branch_tb',
            name='client_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='ActSheetApp.client_tb'),
        ),
    ]
