# Generated by Django 4.1.3 on 2022-11-25 10:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ActSheetApp', '0011_client_tb_remove_branch_tb_location_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='job_tb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=100)),
                ('description', models.TextField(default='')),
                ('start_date', models.DateTimeField(default='', max_length=100)),
                ('end_date', models.DateTimeField(default='', max_length=100)),
                ('actual_start_date', models.DateTimeField(default='', max_length=100)),
                ('actual_end_date', models.DateTimeField(default='', max_length=100)),
                ('created_at', models.CharField(default='', max_length=100)),
                ('updated_at', models.CharField(default='', max_length=100)),
                ('branch_id', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='ActSheetApp.branch_tb')),
                ('client_id', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='ActSheetApp.client_tb')),
                ('team_leader_id', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='ActSheetApp.team_leader_tb')),
            ],
        ),
    ]
