# Generated by Django 4.1.3 on 2022-11-25 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ActSheetApp', '0012_job_tb'),
    ]

    operations = [
        migrations.AddField(
            model_name='job_tb',
            name='job_id',
            field=models.CharField(default='', max_length=100),
        ),
    ]
