# Generated by Django 4.1.3 on 2022-11-28 07:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ActSheetApp', '0013_job_tb_job_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='staff_tb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('email', models.CharField(default='', max_length=100)),
                ('phone', models.CharField(default='', max_length=100)),
                ('designation', models.CharField(default='', max_length=100)),
                ('required_hrs', models.CharField(default='', max_length=100)),
                ('max_break_time', models.CharField(default='', max_length=100)),
                ('status', models.CharField(default='', max_length=100)),
                ('created_at', models.CharField(default='', max_length=100)),
                ('updated_at', models.CharField(default='', max_length=100)),
                ('branch_id', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='ActSheetApp.branch_tb')),
                ('client_id', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='ActSheetApp.client_tb')),
                ('shift_id', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='ActSheetApp.shift_tb')),
            ],
        ),
    ]
