# Generated by Django 4.1.3 on 2022-11-28 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ActSheetApp', '0014_staff_tb'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff_tb',
            name='total_hrs',
            field=models.CharField(default='', max_length=100),
        ),
    ]
