# Generated by Django 4.1.3 on 2022-11-28 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ActSheetApp', '0015_staff_tb_total_hrs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff_tb',
            name='status',
            field=models.CharField(default='', max_length=100, null=True),
        ),
    ]
