# Generated by Django 4.1.3 on 2022-11-29 11:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ActSheetApp', '0017_task_tb'),
    ]

    operations = [
        migrations.AddField(
            model_name='task_tb',
            name='team_leader_id',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='ActSheetApp.team_leader_tb'),
        ),
        migrations.AlterField(
            model_name='task_tb',
            name='agent_id',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='ActSheetApp.agent_tb'),
        ),
    ]
