# Generated by Django 4.1.3 on 2022-11-29 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ActSheetApp', '0018_task_tb_team_leader_id_alter_task_tb_agent_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent_tb',
            name='max_break_time',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='agent_tb',
            name='required_hrs',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='agent_tb',
            name='total_hrs',
            field=models.CharField(default='', max_length=100),
        ),
    ]
