# Generated by Django 4.1.3 on 2022-11-30 11:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ActSheetApp', '0019_agent_tb_max_break_time_agent_tb_required_hrs_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='customer_tb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default='', max_length=100)),
                ('opening_time', models.CharField(default='', max_length=100)),
                ('closing_time', models.CharField(default='', max_length=100)),
                ('customer_id', models.IntegerField(default='', max_length=100)),
                ('customer_entry_time', models.CharField(default='', max_length=100)),
                ('customer_exit_time', models.CharField(default='', max_length=100)),
                ('dwell_time', models.CharField(default='', max_length=100)),
                ('single', models.BooleanField(default=0)),
                ('group', models.BooleanField(default=0)),
                ('male', models.BooleanField(default=0)),
                ('female', models.BooleanField(default=0)),
                ('zone_ids', models.CharField(default='', max_length=100)),
                ('window_zone_ids', models.CharField(default='', max_length=100)),
                ('repeat_customer', models.BooleanField(default='', max_length=100)),
                ('repeat_customer_id', models.IntegerField(default='', max_length=100)),
                ('repeat_customer_visit_date', models.IntegerField(default='', max_length=100)),
                ('tray', models.BooleanField(default=0)),
                ('refreshment', models.BooleanField(default=0)),
                ('gloves', models.BooleanField(default=0)),
                ('backup_stock', models.BooleanField(default=0)),
                ('business_card', models.BooleanField(default=0)),
                ('body_language', models.BooleanField(default=0)),
                ('full_uniform', models.BooleanField(default=0)),
                ('conversion_status', models.BooleanField(default=0)),
                ('conversion_percentage', models.IntegerField(default='', max_length=100)),
                ('invoice_time', models.CharField(default='', max_length=100)),
                ('reason_for_no_conversion', models.TextField(default='')),
                ('remark', models.TextField(default='')),
                ('created_at', models.CharField(default='', max_length=100)),
                ('updated_at', models.CharField(default='', max_length=100)),
                ('agent_id', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='ActSheetApp.agent_tb')),
                ('staff_id', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='ActSheetApp.staff_tb')),
                ('task_id', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='ActSheetApp.task_tb')),
            ],
        ),
    ]
