# Generated by Django 4.1.3 on 2022-12-01 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ActSheetApp', '0021_alter_customer_tb_backup_stock_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer_tb',
            name='female',
            field=models.BooleanField(default=0, max_length=100),
        ),
        migrations.AlterField(
            model_name='customer_tb',
            name='group',
            field=models.BooleanField(default=0, max_length=100),
        ),
        migrations.AlterField(
            model_name='customer_tb',
            name='male',
            field=models.BooleanField(default=0, max_length=100),
        ),
        migrations.AlterField(
            model_name='customer_tb',
            name='single',
            field=models.BooleanField(default=0, max_length=100),
        ),
    ]
