# Generated by Django 4.1.3 on 2022-12-01 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ActSheetApp', '0022_alter_customer_tb_female_alter_customer_tb_group_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer_tb',
            name='submit_tl',
            field=models.BooleanField(default=0, max_length=100),
        ),
    ]
