# Generated by Django 4.1.3 on 2022-12-01 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ActSheetApp', '0023_customer_tb_submit_tl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer_tb',
            name='conversion_percentage',
            field=models.IntegerField(default=''),
        ),
        migrations.AlterField(
            model_name='customer_tb',
            name='customer_id',
            field=models.IntegerField(default=''),
        ),
        migrations.AlterField(
            model_name='customer_tb',
            name='repeat_customer_id',
            field=models.IntegerField(default=''),
        ),
        migrations.AlterField(
            model_name='customer_tb',
            name='repeat_customer_visit_date',
            field=models.DateTimeField(default='', max_length=100),
        ),
    ]
