# Generated by Django 4.1.3 on 2022-12-03 12:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ActSheetApp', '0026_customer_tb_conversion_to'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer_tb',
            old_name='staff_id',
            new_name='staff_ids',
        ),
        migrations.AlterField(
            model_name='customer_tb',
            name='conversion_to',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='ActSheetApp.staff_tb'),
        ),
    ]
