# Generated by Django 4.1.3 on 2022-12-06 11:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ActSheetApp', '0029_remove_customer_tb_branch_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer_tb',
            name='branch_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='ActSheetApp.branch_tb'),
        ),
    ]
