# Generated by Django 4.1.3 on 2022-12-09 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ActSheetApp', '0030_customer_tb_branch_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer_tb',
            name='converted_count',
            field=models.IntegerField(default=0),
        ),
    ]
