# Generated by Django 4.1.3 on 2022-12-09 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ActSheetApp', '0031_customer_tb_converted_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer_tb',
            name='no_of_female',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='customer_tb',
            name='no_of_male',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
