# Generated by Django 4.1.3 on 2022-12-09 18:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ActSheetApp', '0032_customer_tb_no_of_female_customer_tb_no_of_male'),
    ]

    operations = [
        migrations.CreateModel(
            name='staff_attendance_tb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default='', max_length=100)),
                ('in_time', models.CharField(default='', max_length=100)),
                ('out_time', models.CharField(default='', max_length=100)),
                ('break_hours', models.CharField(default='', max_length=100)),
                ('work_hours', models.CharField(default='', max_length=100)),
                ('over_time', models.CharField(default='', max_length=100)),
                ('under_time', models.CharField(default='', max_length=100)),
                ('short_break_in_1', models.CharField(default='', max_length=100, null=True)),
                ('short_break_out_1', models.CharField(default='', max_length=100, null=True)),
                ('short_break_in_2', models.CharField(default='', max_length=100, null=True)),
                ('short_break_out_2', models.CharField(default='', max_length=100, null=True)),
                ('short_break_in_3', models.CharField(default='', max_length=100, null=True)),
                ('short_break_out_3', models.CharField(default='', max_length=100, null=True)),
                ('short_break_in_4', models.CharField(default='', max_length=100, null=True)),
                ('short_break_out_4', models.CharField(default='', max_length=100, null=True)),
                ('staff_id', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='ActSheetApp.staff_tb')),
            ],
        ),
    ]
