# Generated by Django 4.1.3 on 2022-12-14 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ActSheetApp', '0033_staff_attendance_tb'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff_attendance_tb',
            name='created_at',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='staff_attendance_tb',
            name='updated_at',
            field=models.CharField(default='', max_length=100),
        ),
    ]
