# Generated by Django 4.1.3 on 2022-12-19 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ActSheetApp', '0034_staff_attendance_tb_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client_tb',
            name='status',
            field=models.CharField(default='Pending', max_length=100),
        ),
        migrations.AddField(
            model_name='job_tb',
            name='status',
            field=models.CharField(default='Pending', max_length=100),
        ),
    ]
