# Generated by Django 4.1.3 on 2022-12-20 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ActSheetApp', '0037_client_tb_client_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='task_tb',
            name='submit_tl',
            field=models.BooleanField(default=0, max_length=100),
        ),
    ]
