# Generated by Django 4.1.3 on 2022-12-21 15:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ActSheetApp', '0042_task_request_tb'),
    ]

    operations = [
        migrations.CreateModel(
            name='time_period_tb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.CharField(default='', max_length=100)),
                ('updated_at', models.CharField(default='', max_length=100)),
                ('period', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='ActSheetApp.task_tb')),
            ],
        ),
    ]
