# Generated by Django 4.1.3 on 2022-12-22 07:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ActSheetApp', '0046_alter_customer_tb_time_period_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer_tb',
            name='client_id',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='ActSheetApp.client_tb'),
        ),
    ]
