# Generated by Django 4.1.3 on 2022-12-23 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ActSheetApp', '0049_task_tb_have_request'),
    ]

    operations = [
        migrations.AddField(
            model_name='task_tb',
            name='request_status',
            field=models.CharField(default='', max_length=100, null=True),
        ),
    ]
