# Generated by Django 4.1.3 on 2022-12-23 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ActSheetApp', '0054_alter_customer_tb_conversion_percentage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer_tb',
            name='repeat_customer_id',
            field=models.IntegerField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='customer_tb',
            name='repeat_customer_visit_date',
            field=models.DateTimeField(default='', max_length=100, null=True),
        ),
    ]
