# Generated by Django 4.1.3 on 2022-12-23 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ActSheetApp', '0055_alter_customer_tb_repeat_customer_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer_tb',
            name='converted_count',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
