# Generated by Django 4.1.3 on 2022-12-25 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ActSheetApp', '0058_staff_tb_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch_tb',
            name='document',
            field=models.ImageField(null=True, upload_to='image'),
        ),
        migrations.AddField(
            model_name='branch_tb',
            name='layout',
            field=models.ImageField(null=True, upload_to='image'),
        ),
    ]
