# Generated by Django 4.1.3 on 2022-12-25 16:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ActSheetApp', '0060_customer_tb_team_leader_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer_tb',
            name='team_leader_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='ActSheetApp.team_leader_tb'),
        ),
    ]
