# Generated by Django 4.1.3 on 2022-12-25 16:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ActSheetApp', '0061_alter_customer_tb_team_leader_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='delay_task_request_tb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remark', models.TextField(default='')),
                ('status', models.BooleanField(default=0, max_length=100)),
                ('actual_end_date', models.DateTimeField(default='', max_length=100)),
                ('new_end_date', models.DateTimeField(default='', max_length=100, null=True)),
                ('created_at', models.DateTimeField(default='', max_length=100)),
                ('updated_at', models.DateTimeField(default='', max_length=100)),
                ('agent_id', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='ActSheetApp.agent_tb')),
                ('client_id', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='ActSheetApp.client_tb')),
                ('task_id', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='ActSheetApp.task_tb')),
                ('team_leader_id', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='ActSheetApp.team_leader_tb')),
            ],
        ),
    ]
