# Generated by Django 4.1.3 on 2022-12-25 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ActSheetApp', '0062_delay_task_request_tb'),
    ]

    operations = [
        migrations.AddField(
            model_name='delay_task_request_tb',
            name='status_changed_by',
            field=models.CharField(default='', max_length=100),
        ),
    ]
