# Generated by Django 4.1.3 on 2022-12-25 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ActSheetApp', '0064_alter_delay_task_request_tb_status_changed_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='task_tb',
            name='delay_request_status',
            field=models.CharField(default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='task_tb',
            name='have_delay_request',
            field=models.BooleanField(default=0, max_length=100),
        ),
    ]
