# Generated by Django 4.1.3 on 2022-12-25 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ActSheetApp', '0065_task_tb_delay_request_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delay_task_request_tb',
            name='actual_end_date',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='delay_task_request_tb',
            name='new_end_date',
            field=models.CharField(default='', max_length=100, null=True),
        ),
    ]
