# Generated by Django 4.1.3 on 2022-12-25 17:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ActSheetApp', '0066_alter_delay_task_request_tb_actual_end_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='agent_checkin_checkout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default='', max_length=100)),
                ('time', models.CharField(default='', max_length=100)),
                ('status', models.CharField(default='', max_length=100)),
                ('created_at', models.DateTimeField(default='', max_length=100)),
                ('updated_at', models.DateTimeField(default='', max_length=100)),
                ('agent_id', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='ActSheetApp.agent_tb')),
            ],
        ),
    ]
