# Generated by Django 4.1.3 on 2022-12-25 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ActSheetApp', '0067_agent_checkin_checkout'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='agent_checkin_checkout',
            new_name='agent_checkin_checkout_tb',
        ),
    ]
