# Generated by Django 4.1.3 on 2022-12-26 12:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ActSheetApp', '0068_rename_agent_checkin_checkout_agent_checkin_checkout_tb'),
    ]

    operations = [
        migrations.CreateModel(
            name='message_tb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default='', max_length=100)),
                ('time', models.CharField(default='', max_length=100)),
                ('message', models.TextField(default='')),
                ('status', models.CharField(default='', max_length=100)),
                ('created_at', models.DateTimeField(default='', max_length=100)),
                ('updated_at', models.DateTimeField(default='', max_length=100)),
                ('agent_id', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='ActSheetApp.agent_tb')),
                ('client_id', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='ActSheetApp.client_tb')),
                ('team_leader_id', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='ActSheetApp.team_leader_tb')),
            ],
        ),
    ]
