# Generated by Django 4.1.3 on 2022-12-26 12:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ActSheetApp', '0069_message_tb'),
    ]

    operations = [
        migrations.AddField(
            model_name='message_tb',
            name='admin_id',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='ActSheetApp.admin_tb'),
        ),
    ]
