# Generated by Django 4.1.3 on 2022-12-26 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ActSheetApp', '0070_message_tb_admin_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='message_tb',
            name='receiver',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='message_tb',
            name='sender',
            field=models.CharField(default='', max_length=100),
        ),
    ]
