# Generated by Django 4.1.3 on 2022-12-26 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ActSheetApp', '0071_message_tb_receiver_message_tb_sender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer_tb',
            name='date',
            field=models.CharField(default='', max_length=100),
        ),
    ]
