# Generated by Django 4.1.3 on 2022-12-26 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ActSheetApp', '0072_alter_customer_tb_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer_tb',
            name='repeat_customer',
            field=models.BooleanField(default=0, max_length=100),
        ),
    ]
