# Generated by Django 4.1.3 on 2022-12-26 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ActSheetApp', '0073_alter_customer_tb_repeat_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer_tb',
            name='repeat_customer_id',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
