# Generated by Django 4.1.3 on 2022-12-26 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ActSheetApp', '0074_alter_customer_tb_repeat_customer_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer_tb',
            name='repeat_customer_visit_date',
            field=models.CharField(default='', max_length=100, null=True),
        ),
    ]
