# Generated by Django 4.1.3 on 2022-12-26 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ActSheetApp', '0075_alter_customer_tb_repeat_customer_visit_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer_tb',
            name='date',
            field=models.DateTimeField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='customer_tb',
            name='repeat_customer_visit_date',
            field=models.DateTimeField(max_length=100, null=True),
        ),
    ]
