# Generated by Django 4.1.3 on 2022-12-26 23:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ActSheetApp', '0076_alter_customer_tb_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint_ticket_tb',
            name='task_id',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='ActSheetApp.task_tb'),
        ),
    ]
