# Generated by Django 4.1.3 on 2022-12-26 23:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ActSheetApp', '0077_complaint_ticket_tb_task_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint_ticket_tb',
            name='agent_id',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='ActSheetApp.agent_tb'),
        ),
    ]
