# Generated by Django 4.1.3 on 2022-12-27 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ActSheetApp', '0079_notification_tb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer_tb',
            name='reason_for_no_conversion',
            field=models.TextField(default='', null=True),
        ),
    ]
