# Generated by Django 4.1.3 on 2022-12-30 06:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ActSheetApp', '0080_alter_customer_tb_reason_for_no_conversion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job_tb',
            name='branch_id',
        ),
        migrations.AddField(
            model_name='task_tb',
            name='branch_id',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='ActSheetApp.branch_tb'),
        ),
    ]
