# Generated by Django 4.1.3 on 2022-12-30 06:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ActSheetApp', '0081_remove_job_tb_branch_id_task_tb_branch_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task_tb',
            name='branch_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='ActSheetApp.branch_tb'),
        ),
    ]
