# Generated by Django 4.1.3 on 2022-12-30 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ActSheetApp', '0082_alter_task_tb_branch_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job_tb',
            name='actual_end_date',
            field=models.DateTimeField(default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='job_tb',
            name='actual_start_date',
            field=models.DateTimeField(default='', max_length=100, null=True),
        ),
    ]
