# Generated by Django 4.1.3 on 2022-12-30 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ActSheetApp', '0083_alter_job_tb_actual_end_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer_tb',
            name='status',
            field=models.CharField(default='Pending', max_length=100),
        ),
    ]
