# Generated by Django 4.1.3 on 2022-12-30 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ActSheetApp', '0084_customer_tb_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification_tb',
            name='admin_seen',
            field=models.BooleanField(default=0, max_length=100),
        ),
        migrations.AddField(
            model_name='notification_tb',
            name='agent_seen',
            field=models.BooleanField(default=0, max_length=100),
        ),
        migrations.AddField(
            model_name='notification_tb',
            name='client_seen',
            field=models.BooleanField(default=0, max_length=100),
        ),
        migrations.AddField(
            model_name='notification_tb',
            name='team_leader_seen',
            field=models.BooleanField(default=0, max_length=100),
        ),
    ]
