# Generated by Django 4.1.3 on 2023-01-03 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ActSheetApp', '0085_notification_tb_admin_seen_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job_tb',
            name='actual_end_date',
            field=models.CharField(default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='job_tb',
            name='actual_start_date',
            field=models.CharField(default='', max_length=100, null=True),
        ),
    ]
