# Generated by Django 4.1.3 on 2023-01-05 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ActSheetApp', '0089_alter_staff_attendance_tb_client_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff_attendance_break_tb',
            name='remark',
            field=models.TextField(default='', null=True),
        ),
    ]
