# Generated by Django 4.1.3 on 2023-01-05 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ActSheetApp', '0090_staff_attendance_break_tb_remark'),
    ]

    operations = [
        migrations.AddField(
            model_name='delay_task_request_tb',
            name='status_remark',
            field=models.TextField(default='', null=True),
        ),
        migrations.AddField(
            model_name='task_request_tb',
            name='status_remark',
            field=models.TextField(default='', null=True),
        ),
    ]
