# Generated by Django 4.1.3 on 2023-01-10 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ActSheetApp', '0092_staff_attendance_break_tb_break_diff'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff_attendance_tb',
            name='epoch_org_work_hours',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='staff_attendance_tb',
            name='epoch_over_time',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='staff_attendance_tb',
            name='epoch_under_time',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='staff_attendance_tb',
            name='epoch_work_hours',
            field=models.CharField(default='', max_length=100),
        ),
    ]
