# Generated by Django 4.1.3 on 2023-01-16 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ActSheetApp', '0093_staff_attendance_tb_epoch_org_work_hours_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff_attendance_tb',
            name='submit',
            field=models.BooleanField(default=0, max_length=100),
        ),
    ]
