# Generated by Django 4.1.3 on 2023-01-16 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ActSheetApp', '0094_staff_attendance_tb_submit'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff_attendance_break_tb',
            name='in_date',
            field=models.CharField(default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='staff_attendance_break_tb',
            name='out_date',
            field=models.CharField(default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='staff_attendance_tb',
            name='out_date',
            field=models.CharField(default='', max_length=100, null=True),
        ),
    ]
