# Generated by Django 4.1.3 on 2023-01-17 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ActSheetApp', '0095_staff_attendance_break_tb_in_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch_tb',
            name='email',
            field=models.CharField(default='', max_length=100),
        ),
    ]
