# Generated by Django 4.1.3 on 2023-01-30 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ActSheetApp', '0096_branch_tb_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff_attendance_tb',
            name='official_break',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='staff_attendance_tb',
            name='un_official_break',
            field=models.CharField(default='', max_length=100),
        ),
    ]
