# Generated by Django 4.1.3 on 2023-02-10 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ActSheetApp', '0098_client_tb_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='task_tb',
            name='approved_time',
            field=models.DateTimeField(null=True),
        ),
    ]
