# Generated by Django 4.1.3 on 2023-02-10 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ActSheetApp', '0099_task_tb_approved_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch_tb',
            name='cc',
            field=models.TextField(default='', null=True),
        ),
    ]
