# Generated by Django 4.1.3 on 2023-02-24 05:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ActSheetApp', '0101_admin_tb_pin_agent_tb_pin_client_tb_pin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff_attendance_tb',
            name='agent_id',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='ActSheetApp.agent_tb'),
        ),
    ]
