# Generated by Django 4.1.3 on 2023-03-13 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ActSheetApp', '0102_staff_attendance_tb_agent_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff_attendance_tb',
            name='approve',
            field=models.BooleanField(default=0, max_length=100),
        ),
    ]
