# Generated by Django 4.1.3 on 2023-03-13 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ActSheetApp', '0103_staff_attendance_tb_approve'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff_attendance_tb',
            name='approved_time',
            field=models.DateTimeField(null=True),
        ),
    ]
