from django.urls import path,include
from ActSheetApp import views
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
     path('admin-login/', views.adminLogin ,name='admin-login'),
     path('admin-dashboard/', views.adminDashboard, name='admin-dashboard'),
     path('admin-logout/', views.adminLogout, name='admin-logout'),
     path('list-branch/', views.listBranch, name='list-branch'),
     path('add-branch/', views.addNewBranch, name='add-branch'),
     path('edit-branch/', views.updateBranch, name='edit-branch'),
     path('delete-branch/', views.deleteBranch, name='delete-branch'),
     path('list-shift/', views.listAllShift, name='list-shift'),
     path('add-shift/', views.addNewShift, name='add-shift'),
     path('edit-shift/', views.updateShift, name='edit-shift'),
     path('delete-shift/', views.deleteShift, name='delete-shift'),
     path('list-zones/', views.listAllZones, name='list-zones'),
     path('add-zone/', views.addNewZone, name='add-zone'),
     path('edit-zone/', views.updateZone, name='edit-zone'),
     path('delete-zone/', views.deleteZone, name='delete-zone'),
     path('list-window-zones/', views.listAllWindowZones, name='list-window-zones'),
     path('add-window-zones/', views.addNewWindowZone, name='add-window-zone'),
     path('edit-window-zone/', views.updateWindowZone, name='edit-window_zone'),
     path('delete-window-zone/', views.deleteWindowZone, name='delete-window-zone'),
     path('list-team-leader/', views.listTeamLeader, name='list-team-leader'),
     path('add-team-leader/', views.addNewTeamLeader, name='add-team-leader'),
     path('edit-team-leader/', views.updateTeamLeader, name='edit-team-leader'),
     path('delete-team-leader/', views.deleteTeamLeader, name='delete-team-leader'),
     path('list-agent/', views.listAgent, name='list-agent'),
     path('add-agent/', views.addNewAgent, name='add-agent'),
     path('edit-agent/', views.updateAgent, name='edit-agent'),
     path('delete-agent/', views.deleteAgent, name='delete-agent'),
     path('list-client/', views.listClient, name='list-client'),
     path('add-client/', views.addNewClient, name='add-client'),
     path('edit-client/', views.updateClient, name='edit-client'),
     path('delete-client/', views.deleteClient, name='delete-client'),
     path('list-jobs/', views.listJob, name='list-jobs'),
     path('add-job/', views.addNewJob, name='add-job'),
     path('edit-job/', views.updateJob, name='edit-job'),
     path('delete-job/', views.deleteJob, name='delete-job'),
     path('list-staff/', views.listStaff, name='list-staff'),
     path('add-staff/', views.addStaff, name='add-staff'),
     path('edit-staff/', views.updateStaff, name='edit-staff'),
     path('delete-staff/', views.deleteStaff, name='delete-staff'),
     path('list-task/', views.listTask, name='list-task'),
     path('add-task/', views.addNewTask, name='add-task'),
     path('edit-task/', views.updateTask, name='edit-task'),
     path('delete-task/', views.deleteTask, name='delete-task'),
     path('revoke-task/', views.revokeTask, name='revoke-task'),
     path('list-customer/', views.listCustomer, name='list-customer'),
     path('add-customer/', views.addNewCustomer, name='add-customer'),
     path('edit-customer/', views.updateCustomer, name='edit-customer'),
     path('delete-customer/', views.deleteCustomer, name='delete-customer'),
     path('list-attendance/', views.listStaffAttendance, name='list-attendance'),
     path('add-attendance/', views.addAttendance, name='add-attendance'),
     path('delete-attendance/', views.deleteStaffAttendance, name='delete-attendance'),
     path('staff-data/', views.getStaffData, name='staff-data'),
     path('report/', views.getReport, name='report'),
     path('get-filter-category/', views.getFilterCategory, name='get-filter-category'),
     path('user-login/', views.userLogin ,name='user-login'),
     path('agent-dashboard/', views.agentDashboard, name='agent-dashboard'),
     path('view-task/', views.viewTask, name='view-task'),
     path('task-submit/', views.taskSubmitToTeamLeader, name='task-submit'),
     path('user-logout/', views.userLogout, name='user-logout'),
     path('store-clientId/', views.storeClientIdInSession, name='store-clientId'),
     path('team-leader-dashboard/', views.teamLeaderDashboard, name='team-leader-dashboard'),
     path('', views.clientLogin ,name='client-login'),
     path('client-dashboard/', views.clientDashboard, name='client-dashboard'),
     path('client-logout/', views.clientLogout, name='client-logout'),
     path('task-request/', views.taskRequest, name='task-request'),
     path('search-task/', views.searchTask, name='search-task'),
     path('change-request-status/', views.changeStatusOfTaskRequest, name='change-request-status'),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)